version: '3'
services:
  course-service:
    build: ./course-service
    volumes:
      - ./course-service:/app
    ports:
      - 5000:8080
  website:
    image: nginx:alpine
    volumes:
      - ./website:/usr/share/nginx/html
    ports:
      - 5002:80
    depends_on:
      - course-service
    
